package com.springboot.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.*;

@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "images")
public class Image {

	@DynamoDBHashKey(attributeName = "imageId")
    private String imageId;

    @DynamoDBAttribute(attributeName = "userHash")
    private String userHash;

    @DynamoDBAttribute(attributeName = "imageName")
    private String imageName;

	public String getImageId() {
		return imageId;
	}

	public void setImageId(String imageId) {
		this.imageId = imageId;
	}

	public String getUserHash() {
		return userHash;
	}

	public void setUserHash(String userHash) {
		this.userHash = userHash;
	}

	public String getImageName() {
		return imageName;
	}

	public void setImageName(String imageName) {
		this.imageName = imageName;
	}
    
    
}
